pipeline{
    agent any
    stages{
        stage("Stage 1"){
            steps{
                echo "========executing Stage 1========"
            }

        }
        stage("Stage 2"){
            steps{
                echo "========executing Stage 2========"
            }
        }
        stage("Stage 3"){
            steps{
                echo "========executing Stage 3========"
            }
        }
        stage("Stage 4"){
            steps{
                echo "========executing Stage 4========"
            }
        }
        stage("Stage 5"){
            steps{
                echo "========executing Stage 5========"
            }
        }
    }
}