pipeline{
    agent any

    stages{
        stage("Demo"){
            steps{ 
                myFunction("Hello from myFunction!")
            }
        }
    }   
}

def myFunction(String myText){
    echo "myText is: ${myText}"
}