pipeline{
    agent any

    stages{
        stage("Demo"){
            steps{ 
                myFunction("Hello from myFunction!")

                sh """
                    echo "This is a shell command"
                    echo "You can run multiple commands in a single sh step"
                    echo "Just like this!"
                    
                """
            }
        }
    }   
}

def myFunction(String myText){
    echo "myText is: ${myText}"
}